FROM python:3

ENV http_proxy http://wwwproxy.unimelb.edu.au:8000/
ENV https_proxy http://wwwproxy.unimelb.edu.au:8000/
ENV HTTP_PROXY http://wwwproxy.unimelb.edu.au:8000/
ENV HTTPS_PROXY http://wwwproxy.unimelb.edu.au:8000/
ENV no_proxy localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au



COPY . .


RUN pip3 install --upgrade pip
RUN pip3 install tweepy
RUN pip3 install tweet-preprocessor
RUN pip3 install couchdb


CMD ["python3", "streaming_to_couchdb.py"]
